server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /resume.md {
        alias /data/resume.md;
        dav_methods PUT;
        create_full_put_path on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
