server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /resume.json {
        alias /data/resume.json;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
